### ISSUE TITLE
[Bug]錯字

### ISSUE THREAD

**Issue by EF-Lin** [Vincenttainan/CppTeachingNote#1]
[01_introduce.md#命名空間](https://github.com/Vincenttainan/CppTeachingNote/blob/main/01_introduce.md#命名空間)中的錯字，「存」在。
![image](https://github.com/Vincenttainan/CppTeachingNote/assets/79702669/f18b2ee1-b823-4836-9d30-73ef705b05ac)

**Comment by Vincenttainan** [comment]
<img width="385" alt="截圖 2024-06-02 下午10 56 47" src="https://github.com/Vincenttainan/CppTeachingNote/assets/54768760/f46b5785-6e85-480d-b183-8caaa44b4897">
感謝，已更正
